name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd ./nest
          docker build -t aquapaka/ingenious:latest .
          docker push aquapaka/ingenious:latest

      - name: Create .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }}" >> .env
          # URI should be mongodb://database:27017 due to mongo being a service named 'database' inside docker-compose.yml
          echo "MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}" >> .env
          echo "MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> .env
          echo "MONGO_DB_USER=${{ secrets.MONGO_DB_USER }}" >> .env
          echo "MONGO_DB_PASS=${{ secrets.MONGO_DB_PASS }}" >> .env
          echo "PORT=4000" >> .env
          # Add more variables as needed

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: ".env,.docker-compose.yaml"
          target: "~/ingenious-deployment"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/ingenious-deployment
            echo ${{ secrets.VPS_PASSWORD }} | sudo -S docker-compose down
            echo ${{ secrets.VPS_PASSWORD }} | sudo -S docker-compose pull
            echo ${{ secrets.VPS_PASSWORD }} | sudo -S docker-compose up -d

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: false
