name: Release

on:
  push:
    branches:
      - main

permissions: {}
jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'aquapaka/ingenious'
    permissions:
        contents: write # to create release (changesets/action)
        pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: release new version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
